### ISSUE TITLE
Trouble with Quickstart on Ubuntu 20.04

### ISSUE THREAD

**Issue by benrbray** [nodegui/svelte-nodegui-starter#1]
I found this project through a Hacker News [post](https://news.ycombinator.com/item?id=26361423), as I suspect many did today!  I followed the quickstart guide including [these instructions](https://docs.nodegui.org/docs/guides/getting-started#setting-up-on-linux), but am unable to install the dependencies:

```
$ npm install
npm ERR! code 1
npm ERR! path /home/benjamin/projects/svelte-nodegui-starter/node_modules/@nodegui/qode
npm ERR! command failed
npm ERR! command sh -c node install.js

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/benjamin/.npm/_logs/2021-03-06T05_32_53_936Z-debug.log
```

Snippet from the log file:

```
514 info run @nodegui/nodegui@0.25.0 postinstall node_modules/@nodegui/nodegui cross-env npm run setupqt && (node ./scripts/skip.js || npm run prebuild:install || npm run build:addon)
515 info run @nodegui/packer@1.4.1 postinstall node_modules/@nodegui/packer node ./scripts/setupBinaries.js
516 info run @nodegui/qode@2.1.0 postinstall node_modules/@nodegui/qode node install.js
517 info run svelte-preprocess@4.6.9 postinstall node_modules/svelte-preprocess echo "[svelte-preprocess] Don't forget to install the preprocessors packages that will be used: node-sass/sass, stylus, less, postcss & postcss-load-config, coffeescript, pug, etc..."
518 info run svelte-preprocess@4.6.9 postinstall { code: 0, signal: null }
519 timing build:run:postinstall:node_modules/svelte-preprocess Completed in 11ms
520 info run @nodegui/qode@2.1.0 postinstall { code: 1, signal: null }
521 timing reify:rollback:createSparse Completed in 249ms
522 timing reify:rollback:retireShallow Completed in 0ms
523 timing command:install Completed in 2056ms
524 verbose stack Error: command failed
524 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/index.js:64:27)
524 verbose stack     at ChildProcess.emit (events.js:315:20)
524 verbose stack     at maybeClose (internal/child_process.js:1048:16)
524 verbose stack     at Socket.<anonymous> (internal/child_process.js:439:11)
524 verbose stack     at Socket.emit (events.js:315:20)
524 verbose stack     at Pipe.<anonymous> (net.js:673:12)
525 verbose pkgid @nodegui/qode@2.1.0
526 verbose cwd /home/benjamin/projects/svelte-nodegui-starter
527 verbose Linux 5.8.0-44-generic
528 verbose argv "/snap/node/3790/bin/node" "/usr/local/bin/npm" "install"
529 verbose node v14.16.0
530 verbose npm  v7.6.0
531 error code 1
532 error path /home/benjamin/projects/svelte-nodegui-starter/node_modules/@nodegui/qode
533 error command failed
534 error command sh -c node install.js
535 verbose exit 1
```

It appears to be trouble with `@nodegui/qode`.  Any ideas?  Thanks for your help!

**Comment by shirakaba** [comment]
I’m not sure myself – could you please file this issue on the qode repo instead? Someone over there should know what’s going on.
